name: CI/CD - Build and Push to HF Space

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Hugging Face Space Registry
        run: echo "${{ secrets.HF_TOKEN }}" | docker login -u "${{ secrets.HF_USERNAME }}" --password-stdin registry.hf.space

      - name: Build Docker image
        run: |
          LOWERCASE_USER="${{ secrets.HF_USERNAME }}"
          LOWERCASE_USER="${LOWERCASE_USER,,}"
          docker build -t registry.hf.space/${LOWERCASE_USER}-fruit-clustering-api:latest .

      - name: Push to HF Space
        run: |
          LOWERCASE_USER="${{ secrets.HF_USERNAME }}"
          LOWERCASE_USER="${LOWERCASE_USER,,}"
          docker push registry.hf.space/${LOWERCASE_USER}-fruit-clustering-api:latest
